# Generated by Django 2.2.1 on 2019-05-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='pace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
