# Generated by Django 2.2.1 on 2019-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowdata', '0003_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.CharField(blank=True, help_text='Optional. If entered, race will end once one user reaches the distance', max_length=255),
        ),
        migrations.AlterField(
            model_name='race',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
