# Generated by Django 2.2.1 on 2019-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowdata', '0005_auto_20190519_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
