# Generated by Django 2.2.1 on 2019-05-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowdata', '0006_race_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_goal',
            field=models.IntegerField(default=100000, help_text='Monthly goal (m)'),
        ),
    ]
